# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSetCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('image', 'Image Data'), ('text', 'Text Data')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='trainingset',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingset.TrainingSetCollection'),
        ),
    ]
